In [1]:
import numpy as np 

In [5]:
mat1=np.array([[1,3],[4,2]])
mat2=np.array([[2,3,1],[1,6,1],[7,9,1]])
mat3=np.array([[2,1,4,1],[9,1,2,1],[1,2,4,5],[1,8,5,4]])
print(mat1,mat2,mat3)

[[1 3]
 [4 2]] [[2 3 1]
 [1 6 1]
 [7 9 1]] [[2 1 4 1]
 [9 1 2 1]
 [1 2 4 5]
 [1 8 5 4]]


In [32]:
print(mat2[2,1])


9
